tasks:
  - init: |
       pip install poetry dephell
       dephell deps convert --from=pyproject.toml --to=setup.py
       pip install -e .

vscode:
  extensions:
    - albop.dolo-language@0.0.1:3kIHCMgRrQLdEp4cLmH24w==
