tasks:
  - init: pip install poetry dephell
    init: "dephell deps convert --from=pyproject.toml --to=setup.py"
    init: pip install -e .

vscode:
  extensions:
    - albop.dolo-language@0.0.1:3kIHCMgRrQLdEp4cLmH24w==
