site_name: Dolo

theme:
    name: material

nav:
    - Home: index.md
    - Install: installation.md
    - Model API: model_api.md
    - Processes: processes.md
    # - API: mkapi/api/dolo
    - Algorithms:
      - steady_state: steady_state.md
      - perturbation: perturbation.md
      - perfect_foresight: perfect_foresight.md
      - time_iteration: time_iteration.md
      - value_iteration: value_iteration.md


plugins:
  - search # necessary for search to work
  - mkapi

markdown_extensions:
  - mdx_math
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.highlight:
      use_pygments: true
      extend_pygments_lang: [yaml]
  - pymdownx.superfences

extra_css:
    - css/extra.css

extra_javascript:
  # other extra java script
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@3
  - https://cdn.jsdelivr.net/npm/vega-embed@5
