// Generated by Dolo
// Model basename : pyramst


var k,c,z;

varexo x;

parameters alpha,beta,gamma,delta,aa;
alpha = 0.5;
beta = 0.05;
gamma = 0.5;
delta = 0.02;
aa = 0.5;

model;


// eq 1
c + k = (1 - delta)*k(-1) + k(-1)^alpha*(1 + x)*aa;


// eq 2
0 = -c(1)^(-gamma)*(1 - delta + k^(-1 + alpha)*(1 + z(1))*aa*alpha)/(1 + beta) + c^(-gamma);


// eq 3
z = x;
end;

shocks;
var x = 0.0100000000000000 ;
end;

initval;
k = ((beta + delta)/(aa*alpha))^(-1/(1 - alpha));
c = k^alpha*aa - delta*k;
end;
