// Generated by Dolo
// Model basename : anonymous


var y,c,k,a,h,b;

varexo e,u;

parameters beta,rho,alpha,delta,theta,psi,tau;
psi = 0;
beta = 0.99;
alpha = 0.36;
rho = 0.95;
delta = 0.025;
tau = 0.025;
theta = 2.95;

model;


// eq 1
h^(1 + psi)*theta*c = (1 - alpha)*y;


// eq 2
k = ((1 - delta)*k + alpha*y(1)*exp(b(1)))*beta*c*exp(-b(1))*exp(b)/c(1);


// eq 3
y = h^(1 - alpha)*k(-1)^alpha*exp(a);


// eq 4
k = (1 - delta)*k(-1) + (-c + y)*exp(b);


// eq 5
a = rho*a(-1) + tau*b(-1) + e;


// eq 6
b = rho*b(-1) + tau*a(-1) + u;
end;



initval;
k = 11.0836044326;
y = 1.08068253096;
e = 0;
c = 0.803592420142;
b = 0;
u = 0;
h = 0.291756310017;
a = 0;
end;
